### ISSUE TITLE
exponents in fractions

### ISSUE THREAD

**Issue by cukierm** [parkmath/parkmath#25]
Normally, exponents are showing up well.  When in fractions, however, the font size for the exponent is larger than the font size for the base, which makes the fraction difficult to read.  Could you automate a switch in font size for exponents in fractions?  (See problem 42c in the Variation and Proportion lesson.  The issue is also all over the PPE lesson.)

**Comment by anandthakker** [comment]
Ah -- yeah, this is definitely something we should (and almost certainly
can) handle automatically rather than manually.

**Comment by anandthakker** [comment]
> When in fractions, however, the font size for the exponent is larger than the font size for the base

@cukierm is it possible that this has been improved as a by product of the updated equation rendering?  Here is what I'm seeing in the PDFs now:

<img width="170" alt="screen shot 2016-08-14 at 11 13 44 pm" src="https://cloud.githubusercontent.com/assets/4974151/17654809/1fc04e26-6275-11e6-8ad9-c401df4accdb.png">

<img width="214" alt="screen shot 2016-08-14 at 11 13 57 pm" src="https://cloud.githubusercontent.com/assets/4974151/17654806/1d62c4f6-6275-11e6-9e94-b207d0774e81.png">

I do find the difference between base and exponent font size to be less distinct than would be ideal, but it sounds like you were seeing the exponent actually having a _larger_ font(!).  At least from my initial investigation, I think a global solution to this is looking unpromising, but I'll keep poking around.

**Comment by cukierm** [comment]
It looks fine now - sorry about that!

**Comment by cukierm** [comment]
It does continue to be an issue in the Prose previews, which I'm not feeling too concerned about right now.  By the way, something is messed up now in the previews - look at any Development section and it will be obvious.

**Comment by anandthakker** [comment]
Main issue here is fixed.
