### ISSUE TITLE
Fix incorrect math fonts in pdf output

### ISSUE THREAD

**Issue by anandthakker** [parkmath/parkmath#31]
Picking this up as a separate task from #20.  After a little research, it looks like the problem is that our current approach to rendering equations--using MathML--has limited styling support in PrinceXML.  Looks like the workaround in [this post](http://www.princexml.com/forum/topic/2971/using-mathjax-with-princexml) is what we'll probably need to use.

**Comment by anandthakker** [comment]
This is either fixed or, at the very least, very much improved as of https://github.com/parkmath/parkmath/commit/52cacd230e7192dacef42777945b07ff8f61f42f

The downside is that the PDF generation seems to take quite a bit longer in cases where the equations are complicated (like, for instance, in Book 5).

**Comment by anandthakker** [comment]
@cukierm I'm closing this issue, and then we can open individual ones when we encounter specific equation rendering issues.

**Comment by cukierm** [comment]
I’m actually having trouble generating the pdfs at all now.  I tried “Reasoning and Proving I” and gave it 10 minutes, then tried “Functions and Models I” and gave it 20.  All I’m getting is one blank page.

**Comment by anandthakker** [comment]
Argh, okay -- it's working on my Mac, but it sounds like the "Travis"
server doing the automated generation is having trouble. I'll have to debug
tomorrow
