### ISSUE TITLE
punctuation after fractions and radicals

### ISSUE THREAD

**Issue by cukierm** [parkmath/parkmath#34]
In the pdfs, but not the web version, periods that come directly after a fraction appear too close to the fraction. (I've been adding extra spaces when I find this too distracting.) Something similar happens with radicals, where commas look like they're inside the radical.

**Comment by cukierm** [comment]
And just generally, more space after a fraction would look good, even if the equation continues.  When adding two fractions, the plus sign is asymmetrically close to the first fraction.

**Comment by anandthakker** [comment]
@cukierm commit 7d92c3716e49bfe8b04d97f0bdc0bf14a386501a attempts a global fix for this by universally adding 3 pixels of padding to the right of any fraction.  I am _slightly_ wary that this might cause some unintended side effects in other equations, but in my quick spot-checks it seems to be working okay.

**Comment by anandthakker** [comment]
(spot checks were in getting comfortable with trig and PPE)

Closing this, but reopen if it's still a problem.  The specific amount of extra spacing can be modified here: https://github.com/parkmath/parkmath/blob/editing/_sass/_base.scss#L68
