### ISSUE TITLE
"algebra examples" style

### ISSUE THREAD

**Issue by cukierm** [parkmath/parkmath#35]
It looks pretty good, but the roman numerals are not lining up with the text properly.  Could you make it so that the numeral lines up with the first line in the text?

Also, FYI, I surrounded each set of examples with "<div>" tags, and that kept the relevant bits together... before that, the headings and the examples were getting mixed up, out of order.

**Comment by cukierm** [comment]
It looks better now - not confusing.  The text still starts on the line _beneath_ the roman numeral, though.

BTW, I meant to say in my last post that I surrounded each set of examples with div tags.

**Comment by anandthakker** [comment]
Should be lined up now - let me know!

**Comment by cukierm** [comment]
Yep!
