### ISSUE TITLE
Using LaTeX for italics instead of html

### ISSUE THREAD

**Issue by eagilson** [parkmath/parkmath#9]
There are a number of places where $ $ is used to italicize text. This is not advisable for 2 reasons. First, it relies on the MathJax extension, not html for something that html does natively. Second any spaces in the text are removed which destroys the sentence. Recommend converting to &lt;em&gt;blah blah blah &lt;/em&gt; for italics.

**Comment by anandthakker** [comment]
@eagilson Agreed:  `<em>...</em>` is definitely the way to go.

**Comment by anandthakker** [comment]
@eagilson Just occurred to me that, for the case when variable names are single letters, it might be faster to just use $ $ to italicize them for now, and then later, when we're done proofing through all the lessons, to convert them all at once to use &lt;em> with a global search and replace.

**Comment by eagilson** [comment]
For variables I would still use $ $, not &lt;em&gt;, so all math text looks the same. The problem is $ $ is being used for normal italics in the text, which completely breaks the formatting.

**Comment by anandthakker** [comment]
Ah, yes: that's a by-product of the automatic conversion from InDesign.  I'm with you on using $ $ for variables.
